# Generated by Django 2.1.4 on 2019-06-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_pinned_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pinned_group',
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned_groups',
            field=models.TextField(blank=True),
        ),
    ]
