# Generated by Django 2.1.4 on 2019-06-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usergroup_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uID',
            field=models.TextField(blank=True),
        ),
    ]
