# Generated by Django 2.1.4 on 2019-06-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pinned_commentary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentary_pinned', to='api.Comment'),
        ),
    ]
