# Generated by Django 2.1.4 on 2019-07-09 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190701_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_articles_first',
            field=models.BooleanField(default=True),
        ),
    ]
