# Generated by Django 2.1.4 on 2019-07-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190709_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='last_comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
