# Generated by Django 2.1.4 on 2019-07-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_usergroup_last_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='thumbnail_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
